### ISSUE TITLE
init failed on RPI2 and Raspbian Jessie lite

### ISSUE THREAD

**Issue by idreamsi** [Snootlab/lora_chisterapi#1]
After compile, get init failed.
SPI is enable, This code compatible with RFM96 ?
What is the problem ?
![init error](https://cloud.githubusercontent.com/assets/8011806/18005352/b9fbec7e-6bae-11e6-99cf-7f8b97d0c287.png)

**Comment by Snootlab** [comment]
Did you have wiringpi installed ?

I forgot to write it in the README.md but now it's okay.

Here is the tuto on the forum : http://forum.snootlab.com/viewtopic.php?f=59&t=1512

**Comment by idreamsi** [comment]
SPI settings were reset and problem is solved, 
Thanks.
