### ISSUE TITLE
Init failed on RPi3 and LoraHat v1.3

### ISSUE THREAD

**Issue by noesberger** [Snootlab/lora_chisterapi#5]
Hi

I've installed wiringpi, copied the receiver.cpp, run make and then tried to start ./chisterapi. But after that I receive:
Init failed

Anyone with the same problem?

**Comment by sourabhacharya** [comment]
Hi,
Even I'm facing the same problem. Check the photos of my screen below:
![img-20170817-wa0006](https://user-images.githubusercontent.com/22422745/30655170-29f3274a-9dfe-11e7-9505-1def1e14d41d.jpg)
![img-20170817-wa0007](https://user-images.githubusercontent.com/22422745/30655169-29f0dd46-9dfe-11e7-88c1-d1b88dd658a7.jpg)

I also tried typing "make clean" before typing in "make", but still it shows the same error. Did you get to know of any workarounds to get rid of this "Init failed" error? If so, then do let me know.

Thanks,
Sourabh

**Comment by ArthourR** [comment]
Same issue here ...

**Comment by Beetix** [comment]
Hi,

Commit ea36bc2 should fix your issue. If not reopen this issue.

Thanks
