### ISSUE TITLE
Segfault on examples/receiver

### ISSUE THREAD

**Issue by adrianleh** [Snootlab/lora_chisterapi#6]
I am getting the following seg fault on an rpi 2 with a dragino lora/gps hat on raspbian strech:

g++ -std=c++11 -g -Wall -DRH_PLATFORM=RH_PLATFORM_RPI -D__RASPBERRY_PI_ -I lib/radiohead/ -o src/main.o -c src/main.cpp
Makefile:24: recipe for target 'src/main.o' failed
make: *** [src/main.o] Segmentation fault

Does anyone know, what I am doing wrong

**Comment by Beetix** [comment]
Hi,

We would need more information to help you with your issue.

Have you tried using gdb to see where the segfault happens?
